/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   syscall.c                                          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: tettouat <tettouat@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2017/02/24 14:57:08 by tettouat          #+#    #+#             */
/*   Updated: 2017/02/24 15:02:59 by tettouat         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <stdlib.h>

#include "syscall.h"

const syscall_info SYSCALLS[] = {
    { "read", long_, 3, { uint_, string_, ulong_ } },
    { "write", long_, 3, { uint_, string_, ulong_ } },
    { "open", int_, 3, { string_, int_, uint_ } },
    { "close", long_, 1, { uint_ } },
    { "stat", int_, 2, { string_, pointer_ } },
    { "fstat", int_, 2, { uint_, pointer_ } },
    { "lstat", int_, 2, { string_, pointer_ } },
    { "poll", int_, 3, { pointer_, uint_, int_ } },
    { "lseek", long_, 3, { uint_, long_, uint_ } },
    { "mmap", pointer_, 6, { ulong_, ulong_, ulong_, ulong_, ulong_, ulong_ } },
    { "mprotect", int_, 3, { ulong_, ulong_, ulong_ } },
    { "munmap", int_, 2, { ulong_, ulong_ } },
    { "brk", pointer_, 1, { pointer_ } },
    { "rt_sigaction", long_, 4, { int_, pointer_, pointer_, ulong_ } },
    { "rt_sigprocmask", long_, 4, { int_, pointer_, pointer_, ulong_ } },
    { "rt_sigreturn", long_, 0, {  } },
    { "ioctl", int_, 3, { uint_, uint_, ulong_ } },
    { "pread64", long_, 4, { uint_, string_, ulong_, long_ } },
    { "pwrite64", long_, 4, { uint_, string_, ulong_, long_ } },
    { "readv", long_, 3, { ulong_, pointer_, ulong_ } },
    { "writev", long_, 3, { ulong_, pointer_, ulong_ } },
    { "access", int_, 2, { string_, int_ } },
    { "pipe", int_, 1, { pointer_ } },
    { "select", int_, 5, { int_, pointer_, pointer_, pointer_, pointer_ } },
    { "sched_yield", long_, 0, {  } },
    { "mremap", pointer_, 1, { ulong_ } },
    { "msync", int_, 3, { ulong_, ulong_, int_ } },
    { "mincore", int_, 3, { ulong_, ulong_, string_ } },
    { "madvise", long_, 3, { ulong_, ulong_, int_ } },
    { "shmget", int_, 3, { int_, ulong_, int_ } },
    { "shmat", pointer_, 3, { int_, string_, int_ } },
    { "shmctl", int_, 3, { int_, int_, pointer_ } },
    { "dup", int_, 1, { uint_ } },
    { "dup2", int_, 2, { uint_, uint_ } },
    { "pause", long_, 0, {  } },
    { "nanosleep", int_, 2, { pointer_, pointer_ } },
    { "getitimer", int_, 2, { int_, pointer_ } },
    { "alarm", uint_, 1, { uint_ } },
    { "setitimer", int_, 3, { int_, pointer_, pointer_ } },
    { "getpid", long_, 0, {  } },
    { "sendfile", long_, 4, { int_, int_, pointer_, ulong_ } },
    { "socket", int_, 3, { int_, int_, int_ } },
    { "connect", int_, 3, { int_, pointer_, int_ } },
    { "accept", int_, 3, { int_, pointer_, pointer_ } },
    { "sendto", long_, 6, { int_, pointer_, ulong_, uint_, pointer_, int_ } },
    { "recvfrom", long_, 6, { int_, pointer_, ulong_, uint_, pointer_, pointer_ } },
    { "sendmsg", long_, 3, { int_, pointer_, uint_ } },
    { "recvmsg", long_, 3, { int_, pointer_, uint_ } },
    { "shutdown", int_, 2, { int_, int_ } },
    { "bind", int_, 3, { int_, pointer_, int_ } },
    { "listen", int_, 2, { int_, int_ } },
    { "getsockname", int_, 3, { int_, pointer_, pointer_ } },
    { "getpeername", int_, 3, { int_, pointer_, pointer_ } },
    { "socketpair", int_, 4, { int_, int_, int_, pointer_ } },
    { "setsockopt", int_, 5, { int_, int_, int_, string_, int_ } },
    { "getsockopt", int_, 5, { int_, int_, int_, string_, pointer_ } },
    { "clone", int_, 5, { ulong_, ulong_, pointer_, pointer_, int_ } },
    { "fork", long_, 0, {  } },
    { "vfork", long_, 0, {  } },
    { "execve", int_, 3, { string_, array_, array_ } },
    { "exit", long_, 1, { int_ } },
    { "wait4", int_, 4, { int_, pointer_, int_, pointer_ } },
    { "kill", int_, 2, { int_, int_ } },
    { "uname", int_, 1, { pointer_ } },
    { "semget", int_, 3, { int_, int_, int_ } },
    { "semop", int_, 3, { int_, pointer_, uint_ } },
    { "semctl", int_, 4, { int_, int_, int_, ulong_ } },
    { "shmdt", int_, 1, { string_ } },
    { "msgget", int_, 2, { int_, int_ } },
    { "msgsnd", int_, 4, { int_, pointer_, ulong_, int_ } },
    { "msgrcv", long_, 5, { int_, pointer_, ulong_, long_, int_ } },
    { "msgctl", int_, 3, { int_, int_, pointer_ } },
    { "fcntl", int_, 3, { uint_, uint_, ulong_ } },
    { "flock", int_, 2, { uint_, uint_ } },
    { "fsync", int_, 1, { uint_ } },
    { "fdatasync", int_, 1, { uint_ } },
    { "truncate", int_, 2, { string_, long_ } },
    { "ftruncate", int_, 2, { uint_, ulong_ } },
    { "getdents", int_, 3, { uint_, pointer_, uint_ } },
    { "getcwd", long_, 2, { string_, ulong_ } },
    { "chdir", int_, 1, { string_ } },
    { "fchdir", int_, 1, { uint_ } },
    { "rename", int_, 2, { string_, string_ } },
    { "mkdir", int_, 2, { string_, uint_ } },
    { "rmdir", int_, 1, { string_ } },
    { "creat", int_, 2, { string_, uint_ } },
    { "link", int_, 2, { string_, string_ } },
    { "unlink", int_, 1, { string_ } },
    { "symlink", int_, 2, { string_, string_ } },
    { "readlink", long_, 3, { string_, string_, int_ } },
    { "chmod", int_, 2, { string_, uint_ } },
    { "fchmod", int_, 2, { uint_, uint_ } },
    { "chown", int_, 3, { string_, uint_, uint_ } },
    { "fchown", int_, 3, { uint_, uint_, uint_ } },
    { "lchown", int_, 3, { string_, uint_, uint_ } },
    { "umask", long_, 1, { int_ } },
    { "gettimeofday", int_, 2, { pointer_, pointer_ } },
    { "getrlimit", long_, 2, { uint_, pointer_ } },
    { "getrusage", int_, 2, { int_, pointer_ } },
    { "sysinfo", long_, 1, { pointer_ } },
    { "times", ulong_, 1, { pointer_ } },
    { "ptrace", long_, 4, { long_, long_, ulong_, ulong_ } },
    { "getuid", long_, 0, {  } },
    { "syslog", int_, 3, { int_, string_, int_ } },
    { "getgid", long_, 0, {  } },
    { "setuid", int_, 1, { uint_ } },
    { "setgid", int_, 1, { uint_ } },
    { "geteuid", long_, 0, {  } },
    { "getegid", long_, 0, {  } },
    { "setpgid", int_, 2, { int_, int_ } },
    { "getppid", long_, 0, {  } },
    { "getpgrp", int_, 0, {  } },
    { "setsid", long_, 0, {  } },
    { "setreuid", int_, 2, { uint_, uint_ } },
    { "setregid", int_, 2, { uint_, uint_ } },
    { "getgroups", int_, 2, { int_, pointer_ } },
    { "setgroups", int_, 2, { int_, pointer_ } },
    { "setresuid", int_, 3, { uint_, uint_, uint_ } },
    { "getresuid", int_, 3, { pointer_, pointer_, pointer_ } },
    { "setresgid", int_, 3, { uint_, uint_, uint_ } },
    { "getresgid", int_, 3, { pointer_, pointer_, pointer_ } },
    { "getpgid", int_, 1, { int_ } },
    { "setfsuid", int_, 1, { uint_ } },
    { "setfsgid", int_, 1, { uint_ } },
    { "getsid", int_, 1, { int_ } },
    { "capget", int_, 2, { pointer_, pointer_ } },
    { "capset", int_, 2, { pointer_, pointer_ } },
    { "rt_sigpending", long_, 2, { pointer_, ulong_ } },
    { "rt_sigtimedwait", long_, 4, { pointer_, pointer_, pointer_, ulong_ } },
    { "rt_sigqueueinfo", int_, 3, { int_, int_, pointer_ } },
    { "rt_sigsuspend", long_, 2, { pointer_, ulong_ } },
    { "sigaltstack", int_, 2, { pointer_, pointer_ } },
    { "utime", int_, 2, { string_, pointer_ } },
    { "mknod", int_, 3, { string_, uint_, uint_ } },
    { "uselib", int_, 1, { string_ } },
    { "personality", int_, 1, { uint_ } },
    { "ustat", int_, 2, { uint_, pointer_ } },
    { "statfs", int_, 2, { string_, pointer_ } },
    { "fstatfs", int_, 2, { uint_, pointer_ } },
    { "sysfs", int_, 3, { int_, ulong_, ulong_ } },
    { "getpriority", int_, 2, { int_, int_ } },
    { "setpriority", int_, 3, { int_, int_, int_ } },
    { "sched_setparam", int_, 2, { int_, pointer_ } },
    { "sched_getparam", int_, 2, { int_, pointer_ } },
    { "sched_setscheduler", int_, 3, { int_, int_, pointer_ } },
    { "sched_getscheduler", int_, 1, { int_ } },
    { "sched_get_priority_max", int_, 1, { int_ } },
    { "sched_get_priority_min", int_, 1, { int_ } },
    { "sched_rr_get_interval", int_, 2, { int_, pointer_ } },
    { "mlock", int_, 2, { ulong_, ulong_ } },
    { "munlock", int_, 2, { ulong_, ulong_ } },
    { "mlockall", int_, 1, { int_ } },
    { "munlockall", long_, 0, {  } },
    { "vhangup", long_, 0, {  } },
    { "modify_ldt", int_, 3, { int_, pointer_, ulong_ } },
    { "pivot_root", int_, 2, { string_, string_ } },
    { "_sysctl", int_, 1, { pointer_ } },
    { "prctl", int_, 5, { int_, ulong_, ulong_, ulong_, ulong_ } },
    { "arch_prctl", int_, 3, { pointer_, int_, pointer_ } },
    { "adjtimex", int_, 1, { pointer_ } },
    { "setrlimit", long_, 2, { uint_, pointer_ } },
    { "chroot", int_, 1, { string_ } },
    { "sync", long_, 0, {  } },
    { "acct", int_, 1, { string_ } },
    { "settimeofday", int_, 2, { pointer_, pointer_ } },
    { "mount", int_, 5, { string_, string_, string_, ulong_, pointer_ } },
    { "umount2", int_, 2, { string_, int_ } },
    { "swapon", int_, 2, { string_, int_ } },
    { "swapoff", int_, 1, { string_ } },
    { "reboot", int_, 4, { int_, int_, uint_, pointer_ } },
    { "sethostname", int_, 2, { string_, int_ } },
    { "setdomainname", long_, 2, { string_, int_ } },
    { "iopl", int_, 1, { uint_ } },
    { "ioperm", int_, 3, { ulong_, ulong_, int_ } },
    { "create_module", ulong_, 0, {  } },
    { "init_module", int_, 3, { pointer_, ulong_, string_ } },
    { "delete_module", int_, 2, { string_, uint_ } },
    { "get_kernel_syms", int_, 0, {  } },
    { "query_module", long_, 0, {  } },
    { "quotactl", int_, 4, { uint_, string_, uint_, pointer_ } },
    { "nfsservctl", long_, 0, {  } },
    { "getpmsg", long_, 0, {  } },
    { "putpmsg", long_, 0, {  } },
    { "afs_syscall", long_, 0, {  } },
    { "tuxcall", long_, 0, {  } },
    { "security", long_, 0, {  } },
    { "gettid", long_, 0, {  } },
    { "readahead", long_, 3, { int_, long_, ulong_ } },
    { "setxattr", long_, 5, { string_, string_, pointer_, ulong_, int_ } },
    { "lsetxattr", long_, 5, { string_, string_, pointer_, ulong_, int_ } },
    { "fsetxattr", long_, 5, { int_, string_, pointer_, ulong_, int_ } },
    { "getxattr", long_, 4, { string_, string_, pointer_, ulong_ } },
    { "lgetxattr", long_, 4, { string_, string_, pointer_, ulong_ } },
    { "fgetxattr", long_, 4, { int_, string_, pointer_, ulong_ } },
    { "listxattr", long_, 3, { string_, string_, ulong_ } },
    { "llistxattr", long_, 3, { string_, string_, ulong_ } },
    { "flistxattr", long_, 3, { int_, string_, ulong_ } },
    { "removexattr", long_, 2, { string_, string_ } },
    { "lremovexattr", long_, 2, { string_, string_ } },
    { "fremovexattr", long_, 2, { int_, string_ } },
    { "tkill", int_, 2, { int_, int_ } },
    { "time", ulong_, 1, { pointer_ } },
    { "futex", int_, 6, { pointer_, int_, uint_, pointer_, pointer_, uint_ } },
    { "sched_setaffinity", int_, 3, { int_, uint_, pointer_ } },
    { "sched_getaffinity", int_, 3, { int_, uint_, pointer_ } },
    { "set_thread_area", int_, 1, { pointer_ } },
    { "io_setup", int_, 2, { uint_, pointer_ } },
    { "io_destroy", int_, 1, { ulong_ } },
    { "io_getevents", int_, 5, { ulong_, long_, long_, pointer_, pointer_ } },
    { "io_submit", int_, 3, { ulong_, long_, pointer_ } },
    { "io_cancel", int_, 3, { ulong_, pointer_, pointer_ } },
    { "get_thread_area", int_, 1, { pointer_ } },
    { "lookup_dcookie", int_, 3, { ulong_, string_, ulong_ } },
    { "epoll_create", int_, 1, { int_ } },
    { "epoll_ctl_old", long_, 0, {  } },
    { "epoll_wait_old", long_, 0, {  } },
    { "remap_file_pages", int_, 5, { ulong_, ulong_, ulong_, ulong_, ulong_ } },
    { "getdents64", long_, 3, { uint_, pointer_, uint_ } },
    { "set_tid_address", long_, 1, { pointer_ } },
    { "restart_syscall", long_, 0, {  } },
    { "semtimedop", int_, 4, { int_, pointer_, uint_, pointer_ } },
    { "fadvise64", long_, 4, { int_, long_, ulong_, int_ } },
    { "timer_create", int_, 3, { int_, pointer_, pointer_ } },
    { "timer_settime", int_, 4, { ulong_, int_, pointer_, pointer_ } },
    { "timer_gettime", int_, 2, { ulong_, pointer_ } },
    { "timer_getoverrun", int_, 1, { ulong_ } },
    { "timer_delete", int_, 1, { ulong_ } },
    { "clock_settime", int_, 2, { int_, pointer_ } },
    { "clock_gettime", int_, 2, { int_, pointer_ } },
    { "clock_getres", int_, 2, { int_, pointer_ } },
    { "clock_nanosleep", int_, 4, { int_, int_, pointer_, pointer_ } },
    { "exit_group", long_, 1, { int_ } },
    { "epoll_wait", int_, 4, { int_, pointer_, int_, int_ } },
    { "epoll_ctl", int_, 4, { int_, int_, int_, pointer_ } },
    { "tgkill", int_, 3, { int_, int_, int_ } },
    { "utimes", int_, 2, { string_, pointer_ } },
    { "vserver", long_, 0, {  } },
    { "mbind", int_, 6, { ulong_, ulong_, ulong_, pointer_, ulong_, uint_ } },
    { "set_mempolicy", long_, 3, { int_, pointer_, ulong_ } },
    { "get_mempolicy", int_, 5, { pointer_, pointer_, ulong_, ulong_, ulong_ } },
    { "mq_open", long_, 4, { string_, int_, uint_, pointer_ } },
    { "mq_unlink", long_, 1, { string_ } },
    { "mq_timedsend", long_, 5, { ulong_, string_, ulong_, uint_, pointer_ } },
    { "mq_timedreceive", long_, 5, { ulong_, string_, ulong_, pointer_, pointer_ } },
    { "mq_notify", long_, 2, { ulong_, pointer_ } },
    { "mq_getsetattr", int_, 3, { ulong_, pointer_, pointer_ } },
    { "kexec_load", long_, 4, { ulong_, ulong_, pointer_, ulong_ } },
    { "waitid", int_, 5, { int_, int_, pointer_, int_, pointer_ } },
    { "add_key", int_, 5, { string_, string_, pointer_, ulong_, int_ } },
    { "request_key", int_, 4, { string_, string_, string_, int_ } },
    { "keyctl", long_, 5, { int_, ulong_, ulong_, ulong_, ulong_ } },
    { "ioprio_set", int_, 3, { int_, int_, int_ } },
    { "ioprio_get", int_, 2, { int_, int_ } },
    { "inotify_init", long_, 0, {  } },
    { "inotify_add_watch", int_, 3, { int_, string_, uint_ } },
    { "inotify_rm_watch", int_, 2, { int_, int_ } },
    { "migrate_pages", long_, 4, { int_, ulong_, pointer_, pointer_ } },
    { "openat", int_, 4, { int_, string_, int_, uint_ } },
    { "mkdirat", int_, 3, { int_, string_, uint_ } },
    { "mknodat", int_, 4, { int_, string_, uint_, uint_ } },
    { "fchownat", int_, 5, { int_, string_, uint_, uint_, int_ } },
    { "futimesat", int_, 3, { int_, string_, pointer_ } },
    { "newfstatat", long_, 4, { int_, string_, pointer_, int_ } },
    { "unlinkat", int_, 3, { int_, string_, int_ } },
    { "renameat", int_, 4, { int_, string_, int_, string_ } },
    { "linkat", int_, 5, { int_, string_, int_, string_, int_ } },
    { "symlinkat", int_, 3, { string_, int_, string_ } },
    { "readlinkat", int_, 4, { int_, string_, string_, int_ } },
    { "fchmodat", int_, 3, { int_, string_, uint_ } },
    { "faccessat", int_, 3, { int_, string_, int_ } },
    { "pselect6", long_, 6, { int_, pointer_, pointer_, pointer_, pointer_, pointer_ } },
    { "ppoll", int_, 5, { pointer_, uint_, pointer_, pointer_, ulong_ } },
    { "unshare", int_, 1, { ulong_ } },
    { "set_robust_list", long_, 2, { pointer_, ulong_ } },
    { "get_robust_list", long_, 3, { int_, pointer_, pointer_ } },
    { "splice", long_, 6, { int_, pointer_, int_, pointer_, ulong_, uint_ } },
    { "tee", long_, 4, { int_, int_, ulong_, uint_ } },
    { "sync_file_range", int_, 4, { int_, long_, long_, uint_ } },
    { "vmsplice", long_, 4, { int_, pointer_, ulong_, uint_ } },
    { "move_pages", long_, 6, { int_, ulong_, pointer_, pointer_, pointer_, int_ } },
    { "utimensat", int_, 4, { int_, string_, pointer_, int_ } },
    { "epoll_pwait", int_, 6, { int_, pointer_, int_, int_, pointer_, ulong_ } },
    { "signalfd", int_, 3, { int_, pointer_, ulong_ } },
    { "timerfd_create", int_, 2, { int_, int_ } },
    { "eventfd", int_, 1, { uint_ } },
    { "fallocate", int_, 4, { int_, int_, long_, long_ } },
    { "timerfd_settime", int_, 4, { int_, int_, pointer_, pointer_ } },
    { "timerfd_gettime", int_, 2, { int_, pointer_ } },
    { "accept4", int_, 4, { int_, pointer_, pointer_, int_ } },
    { "signalfd4", long_, 4, { int_, pointer_, ulong_, int_ } },
    { "eventfd2", long_, 2, { uint_, int_ } },
    { "epoll_create1", int_, 1, { int_ } },
    { "dup3", int_, 3, { uint_, uint_, int_ } },
    { "pipe2", int_, 2, { pointer_, int_ } },
    { "inotify_init1", int_, 1, { int_ } },
    { "preadv", long_, 5, { ulong_, pointer_, ulong_, ulong_, ulong_ } },
    { "pwritev", long_, 5, { ulong_, pointer_, ulong_, ulong_, ulong_ } },
    { "rt_tgsigqueueinfo", int_, 4, { int_, int_, int_, pointer_ } },
    { "perf_event_open", int_, 5, { pointer_, int_, int_, int_, ulong_ } },
    { "recvmmsg", int_, 5, { int_, pointer_, uint_, uint_, pointer_ } },
    { "fanotify_init", long_, 2, { uint_, uint_ } },
    { "fanotify_mark", long_, 5, { int_, uint_, ulong_, int_, string_ } },
    { "prlimit64", long_, 4, { int_, uint_, pointer_, pointer_ } },
    { "name_to_handle_at", long_, 5, { int_, string_, pointer_, pointer_, int_ } },
    { "open_by_handle_at", long_, 3, { int_, pointer_, int_ } },
    { "clock_adjtime", long_, 2, { int_, pointer_ } },
    { "syncfs", int_, 1, { int_ } },
    { "sendmmsg", int_, 4, { int_, pointer_, uint_, uint_ } },
    { "setns", int_, 2, { int_, int_ } },
    { "getcpu", int_, 3, { pointer_, pointer_, pointer_ } },
    { "process_vm_readv", long_, 6, { int_, pointer_, ulong_, pointer_, ulong_, ulong_ } },
    { "process_vm_writev", long_, 6, { int_, pointer_, ulong_, pointer_, ulong_, ulong_ } },
    { "kcmp", int_, 5, { int_, int_, int_, ulong_, ulong_ } },
    { "finit_module", int_, 3, { int_, string_, int_ } },
};

const syscall_info *get_syscall_info(long syscall_id)
{
    const syscall_info *info;

    info = NULL;
    if (syscall_id < SYSCALLS_INFO_COUNT)
        info = SYSCALLS + syscall_id;

    return (info);
}
